[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "./src"

[context.production.environment]
  NODE_VERSION = '17.0.1'
  NPM_VERSION = '8.1.3'

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200